### Запрос всех предложений
GET http://localhost:4000/offers
Accept: application/json

### Запрос одного предложения
GET http://localhost:4000/offers/62743c1be73040cb770cb474
Accept: application/json

### Обновление данных предложения
PATCH http://localhost:4000/offers/62743c1be73040cb770cb474
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

{
  "title": "Объявление отредактировано",
  "rating": 4.3,
  "type": "62743c1be73040cb770cb477",
  "goods": [
    "62743c1be73040cb770cb469",
    "62743c1be73040cb770cb46c"
  ]
}

### Добавление нового комментария
POST http://localhost:4000/offers/62743c1be73040cb770cb474/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

{
  "text": "Новый комментарий12312"
}

### Запрос комментариев к предложению
GET http://localhost:4000/offers/62743c1be73040cb770cb474/comments
Accept: application/json

### Обновление комментария
PATCH http://localhost:4000/offers/62743c1be73040cb770cb474/comments/6291343e47db59794a4f6e85
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

{
  "rating": 5
}

### Удаление комментария
DELETE http://localhost:4000/offers/62743c1be73040cb770cb474/comments/629137d93a1f9222053fcdc8
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

### Добавление предложения в избранное
POST http://localhost:4000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

{
  "offerId": "62743c1be73040cb770cb474"
}

### Запрос предложений из избранного
GET http://localhost:4000/favorites
Accept: application/json

### Удаление предложения из избранного
DELETE http://localhost:4000/favorites/6291343e47db59794a4f6e85
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTM3NTIzMTl9._dGxw5xxG5PeeHOqwZ1MDA9BvrhR_0lPSEvBm5iZA-8
Content-Type: application/json

### Добавление нового пользователя
POST http://localhost:4000/users
Content-Type: application/json

{
  "email": "andrey@example.ru",
  "name": "Andrey Pechennikov",
  "isPro": true,
  "password": "654321"
}

### Авторизация пользователя
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "andrey@example.ru",
  "password": "654321"
}

### Обновление токенов
POST http://localhost:4000/users/refresh
Content-Type: application/json

{
  "email": "antonio@example.ru",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyNzQzYzFiZTczMDQwY2I3NzBjYjQ2NiIsImVtYWlsIjoiYW50b25pb0BleGFtcGxlLnJ1IiwiaWF0IjoxNjUzNzUxNDE5LCJleHAiOjE2NTYzNDM0MTl9.rf31CryR2xU6c2sGJxDPPRtf63SmDsM7mBPwmQiw2Hg"
}

### Отзыв токенов - логаут
POST http://localhost:4000/users/logout
Content-Type: application/json

{
  "email": "antonio@example.ru",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjYyOTI0MWJjZDMwOWU1NmI3NWZjYjZkNyIsImVtYWlsIjoiYXBAZGV2YW5keS5tZSIsImlhdCI6MTY1Mzc1MjMzMSwiZXhwIjoxNjU2MzQ0MzMxfQ.2hlGqeIk6KrMTK62uPGgbm1tzq_BgKowC3KUOryOxu0"
}
