const PREVIEW_MIN_LENGTH = 10;
const IMAGE_MIN_COUNT = 6;
const IMAGE_MAX_COUNT = 6;
const TITLE_MIN_LENGTH = 10;
const TITLE_MAX_LENGTH = 100;
const DESCRIPTION_MIN_LENGTH = 20;
const DESCRIPTION_MAX_LENGTH = 1024;
const RATING_MIN = 1;
const RATING_MAX = 5;
const ROOMS_MIN = 1;
const ROOMS_MAX = 8;
const ADULTS_MIN = 1;
const ADULTS_MAX = 10;
const PRICE_MIN = 100;
const PRICE_MAX = 100000;

export {
  PREVIEW_MIN_LENGTH,
  IMAGE_MIN_COUNT,
  IMAGE_MAX_COUNT,
  TITLE_MIN_LENGTH,
  TITLE_MAX_LENGTH,
  DESCRIPTION_MIN_LENGTH,
  DESCRIPTION_MAX_LENGTH,
  RATING_MIN,
  RATING_MAX,
  ROOMS_MIN,
  ROOMS_MAX,
  ADULTS_MIN,
  ADULTS_MAX,
  PRICE_MIN,
  PRICE_MAX
};
